// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcEpSc5XQMuxoPMOiq8D27EoE34rrcc90',
    appId: '1:620573421658:web:4617c117c8ca3402596863',
    messagingSenderId: '620573421658',
    projectId: 'fypproject-4119b',
    authDomain: 'fypproject-4119b.firebaseapp.com',
    storageBucket: 'fypproject-4119b.firebasestorage.app',
    measurementId: 'G-EV7KXDNVWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4zcgMNKoWIr0Dvy88J0kbAca0ty87hs',
    appId: '1:620573421658:android:4ad05c2d5d182da9596863',
    messagingSenderId: '620573421658',
    projectId: 'fypproject-4119b',
    storageBucket: 'fypproject-4119b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvdUXjVdbYP1-YIlOG6JwqliCG0CgfryY',
    appId: '1:620573421658:ios:9fcf5d6da441a6e5596863',
    messagingSenderId: '620573421658',
    projectId: 'fypproject-4119b',
    storageBucket: 'fypproject-4119b.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvdUXjVdbYP1-YIlOG6JwqliCG0CgfryY',
    appId: '1:620573421658:ios:9fcf5d6da441a6e5596863',
    messagingSenderId: '620573421658',
    projectId: 'fypproject-4119b',
    storageBucket: 'fypproject-4119b.firebasestorage.app',
    iosBundleId: 'com.example.fypProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcEpSc5XQMuxoPMOiq8D27EoE34rrcc90',
    appId: '1:620573421658:web:2457deb8830ca54a596863',
    messagingSenderId: '620573421658',
    projectId: 'fypproject-4119b',
    authDomain: 'fypproject-4119b.firebaseapp.com',
    storageBucket: 'fypproject-4119b.firebasestorage.app',
    measurementId: 'G-S1PDN8ZKGG',
  );
}
