// import 'package:flutter/material.dart';
// import 'package:fyp_project/models/view_report_model.dart';
// import 'package:pdf/widgets.dart' as pw;
// import 'package:pdf/pdf.dart';
// import 'package:open_file/open_file.dart';
// import 'package:path_provider/path_provider.dart';
// import 'dart:io';
// import 'package:flutter/services.dart' show rootBundle;

// class ReportProvider extends ChangeNotifier {
//   Future<void> generatePdf(
//     BuildContext context,
//     ViewReportModel report,
//   ) async {
//     final pdf = pw.Document();

//     // Load font
//     final fontData =
//         await rootBundle.load("assets/fonts/Raleway-MediumItalic.ttf");
//     final ralewayFont = pw.Font.ttf(fontData);

//     pdf.addPage(
//       pw.Page(
//         margin: const pw.EdgeInsets.all(32),
//         build: (pw.Context ctx) => pw.Column(
//           crossAxisAlignment: pw.CrossAxisAlignment.start,
//           children: [
//             pw.Center(
//               child: pw.Text(
//                 'Medical Prediction Report',
//                 style: pw.TextStyle(
//                   fontSize: 26,
//                   fontWeight: pw.FontWeight.bold,
//                   font: ralewayFont,
//                   color: PdfColors.blue800,
//                 ),
//               ),
//             ),
//             pw.SizedBox(height: 18),
//             pw.Container(
//               decoration: pw.BoxDecoration(
//                 color: PdfColors.blue50,
//                 borderRadius: pw.BorderRadius.circular(12),
//               ),
//               padding: const pw.EdgeInsets.all(18),
//               child: pw.Column(
//                 crossAxisAlignment: pw.CrossAxisAlignment.start,
//                 children: [
//                   pw.Text(
//                     "Patient Information",
//                     style: pw.TextStyle(
//                       fontSize: 16,
//                       fontWeight: pw.FontWeight.bold,
//                       color: PdfColors.blue800,
//                       font: ralewayFont,
//                     ),
//                   ),
//                   pw.Divider(height: 18, thickness: 1),
//                   _pdfInfoRow("Name", report.name, ralewayFont),
//                   _pdfInfoRow("Email", report.email, ralewayFont),
//                   _pdfInfoRow("Phone", report.phone, ralewayFont),
//                   _pdfInfoRow("Age", report.age, ralewayFont),
//                   _pdfInfoRow("Gender", report.gender, ralewayFont),
//                 ],
//               ),
//             ),
//             pw.SizedBox(height: 24),
//             pw.Container(
//               decoration: pw.BoxDecoration(
//                 color: PdfColors.green50,
//                 borderRadius: pw.BorderRadius.circular(12),
//               ),
//               padding: const pw.EdgeInsets.all(18),
//               child: pw.Column(
//                 crossAxisAlignment: pw.CrossAxisAlignment.start,
//                 children: [
//                   pw.Text(
//                     "Prediction Result",
//                     style: pw.TextStyle(
//                       fontSize: 16,
//                       fontWeight: pw.FontWeight.bold,
//                       color: PdfColors.green800,
//                       font: ralewayFont,
//                     ),
//                   ),
//                   pw.Divider(height: 18, thickness: 1),
//                   pw.Center(
//                     child: pw.Text(
//                       report.prediction,
//                       style: pw.TextStyle(
//                         fontSize: 20,
//                         fontWeight: pw.FontWeight.bold,
//                         color: PdfColors.blue800,
//                         font: ralewayFont,
//                       ),
//                     ),
//                   ),
//                 ],
//               ),
//             ),
//             pw.Spacer(),
//             pw.Align(
//               alignment: pw.Alignment.centerRight,
//               child: pw.Text(
//                 "Generated by Brain Tumor Detection App",
//                 style: pw.TextStyle(
//                   fontSize: 12,
//                   fontStyle: pw.FontStyle.italic,
//                   color: PdfColors.blueGrey700,
//                   font: ralewayFont,
//                 ),
//               ),
//             ),
//           ],
//         ),
//       ),
//     );

//     final output = await getTemporaryDirectory();
//     final file = File('${output.path}/prediction_report.pdf');
//     await file.writeAsBytes(await pdf.save());

//     ScaffoldMessenger.of(context).showSnackBar(
//       SnackBar(
//         content: Text('PDF Report saved: ${file.path}'),
//         action: SnackBarAction(
//           label: 'Open',
//           onPressed: () {
//             OpenFile.open(file.path);
//           },
//         ),
//       ),
//     );
//   }

//   pw.Widget _pdfInfoRow(String label, String value, pw.Font font) {
//     return pw.Padding(
//       padding: const pw.EdgeInsets.symmetric(vertical: 4),
//       child: pw.Row(
//         children: [
//           pw.Container(
//             width: 70,
//             child: pw.Text(
//               "$label:",
//               style: pw.TextStyle(
//                 fontWeight: pw.FontWeight.bold,
//                 fontSize: 13,
//                 font: font,
//               ),
//             ),
//           ),
//           pw.Expanded(
//             child: pw.Text(
//               value,
//               style: pw.TextStyle(
//                 fontSize: 13,
//                 font: font,
//               ),
//             ),
//           ),
//         ],
//       ),
//     );
//   }
// }
